name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v -o ./Build/Paimon

    - name: Test
      run: go test -v ./...

    - name: Copy Dockerfile
      run: cp dockerfile Build/
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Linux-Paimon
        path: ./Build

  dockerfile:
    name: Build Image
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get artifacts
      uses: actions/download-artifact@v2
      with:
        name: Linux-Paimon
    
    - name: Display structure of downloaded files
      run: ls -R

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: zzlwd/paimon:latest